LINKERFLAGS = -Xlinker --enable-auto-import

all: izvoriste postavke
	
izvoriste: izvoriste.cpp izvoriste.conf postavke setup
	g++ -o output/izvoriste.exe $(LINKERFLAGS) izvoriste.cpp
	
izvoriste.conf: izvoriste.ini
	@cp izvoriste.ini output/izvoriste.ini
	
postavke: postavke.h

setup:
	@-test -d output || mkdir output