LINKERFLAGS = -Xlinker --enable-auto-import

all: izvoriste koderInformacije kanal dekoderInformacije generatorVektoraPogreske koderKanala dekoderKanala

koderKanala: src/koderKanala.cpp
	g++ -o output/z_kod $(LINKERFLAGS) src/koderKanala.cpp

dekoderKanala: src/dekoderKanala.cpp
	g++ -o output/z_dekod $(LINKERFLAGS) src/dekoderKanala.cpp

generatorVektoraPogreske: src/generatorVektoraPogreske.cpp
	g++ -o output/generatorVektoraPogreske $(LINKERFLAGS) src/generatorVektoraPogreske.cpp
	
dekoderInformacije: src/dekoderInformacije.cpp
	g++ -o output/ent_dekod $(LINKERFLAGS) src/dekoderInformacije.cpp
	
kanal: src/kanal.cpp
	g++ -o output/kanal $(LINKERFLAGS) src/kanal.cpp
	
koderInformacije: src/koderInformacije.cpp
	g++ -o output/ent_kod $(LINKERFLAGS) src/koderInformacije.cpp

izvoriste: src/izvoriste.cpp setup
	g++ -o output/izvor $(LINKERFLAGS) src/izvoriste.cpp

setup:
	@-test -d output || mkdir output