LINKERFLAGS = -Xlinker --enable-auto-import

all: izvoriste koderInformacije dekoderInformacije
	
dekoderInformacije: src/dekoderInformacije.cpp dekoderInformacije.conf
	g++ -o output/dekoderInformacije $(LINKERFLAGS) src/dekoderInformacije.cpp
	
dekoderInformacije.conf:
	@cp src/dekoderInformacije.ini output/dekoderInformacije.ini
	
koderInformacije: src/koderInformacije.cpp koderInformacije.conf
	g++ -o output/koderInformacije.exe $(LINKERFLAGS) src/koderInformacije.cpp

koderInformacije.conf:
	@cp src/koderInformacije.ini output/koderInformacije.ini
	
izvoriste: src/izvoriste.cpp izvoriste.conf setup
	g++ -o output/izvoriste.exe $(LINKERFLAGS) src/izvoriste.cpp
	
izvoriste.conf: src/izvoriste.ini
	@cp src/izvoriste.ini output/izvoriste.ini

setup:
	@-test -d output || mkdir output